baseURL: "https://WordsonRobert.github.io/IDENTITY2/"
title: "Identity | Maths Club of IISER Kolkata"
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: about/
      weight: 2
    - name: Contact
      url: contact/
      weight: 3
    - name: Blog
      url: blog/
      weight: 4

params:
  description: "Official website of the Maths Club of IISER Kolkata."
  author: Maths Club of IISER Kolkata
  DateFormat: "2 January 2006"
  defaultTheme: light
  hideFooter: false
  disableThemeToggle: false 
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: false
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  MainSections: ["blog", "talks"]
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: true 
  math: true
  profileMode:
      enabled: false 

  socialIcons:
      - name: Email
        url: mailto:maths.club@iiserkol.ac.in
      - name: YouTube
        url: https://youtube.com/
      - name: Facebook
        url: https://facebook.com/
      - name: Twitter
        url: https://twitter.com/
      - name: Instagram
        url: https://instagram.com/

  assets:
      disableScrollBarStyle: true
  cover:
      hiddenInList: false
      hiddenInSingle: true
  label:
    text: "Identity"
    icon: favicon.ico
    iconHeight: 18

markup:
  goldmark:
      renderer:
          unsafe: true
  highlight:
      guessSyntax: true
      style: autumn 
  tableOfContents:
      endLevel: 2
      ordered: false
      startLevel: 2
