baseURL: "https://WordsonRobert.github.io/IDENTITY2/"
title: "Identity | Maths Club of IISER Kolkata"
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: about/
      weight: 2
    - name: Contact
      url: contact/
      weight: 3
    - name: Blog
      url: blog/
      weight: 4

params:
  env: production
  description: "Official website of the Maths Club of IISER Kolkata."
  author: Maths Club of IISER Kolkata
  defaultTheme: light
  disableThemeToggle: true
  
  homeInfoParams:
    Title: "Identity"
    Content: "Welcome to the official website of the Maths Club of IISER Kolkata. We host discussions, articles, and talks on various mathematical concepts."

  profileMode:
      enabled: false 

  socialIcons:
      - name: Email
        url: mailto:maths.club@iiserkol.ac.in
      - name: YouTube
        url: https://youtube.com/
      - name: Facebook
        url: https://facebook.com/
      - name: Twitter
        url: https://twitter.com/
      - name: Instagram
        url: https://instagram.com/

  assets:
      disableScrollBarStyle: true
  label:
    text: "Identity"

markup:
  goldmark:
      renderer:
          unsafe: true
  highlight:
      guessSyntax: true
      style: autumn
